gems:    ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'vendor']
permalink: '/blog/:year-:month-:day-:title.html'
url: 'http://code.fanxhe.com'

categorizer:
  dir:          categories
  layout:       post_list_category
