gems:    ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'vendor']
environment:
  test:
    url: 'https://test.fanxhe.com'
  development:
    url: 'http://localhost:4000'
  production:
    url: 'https://code.fanxhe.com'
